version: "3.7"

services:
  cserver:
    build: ./cserver
    container_name: cserver
    volumes:
      - ./UDP_server.c:/root/app/server.c
    command: bash -c "cd /root/app/ && gcc server.c -o server && ./server"
    networks:
      hogar:
        ipv4_address: 1.0.0.5

  client:
    build: ./cliente
    container_name: cliente
    command: bash -c "nslookup www.facebook.com"
    depends_on:
      - cserver
    volumes:
      - ./cliente/resolv.conf:/etc/resolv.conf
    networks:
      - hogar

networks:
  hogar:
    ipam:
      config:
        - subnet: 1.0.0.0/29