version: "3.7"

services:
  api:
    container_name: python-todos-api
    image: python
    environment:
      - MONGO_URI=mongodb://mongo:27017/todos
      - APP_PORT=5000
    depends_on:
      - mongo
    volumes:
      - .:/api
    ports: ["5000:5000"]
    tty: true

  mongo:
    container_name: mongo-db
    image: mongo
    volumes:
      - "./db:/data/db"

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    restart: always
    environment:
      - xpack.security.enable=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data-volume:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.4.0
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

volumes:
  elasticsearch-data-volume:
    driver: local