version: '3.7' #sudo docker-compose up -d     #sudo docker-compose build

services:
  cserver:
    build: ./cserver
    container_name: cserver
    volumes:
      - ./cserver/UDP_server.c:/root/app/server.c
    command: bash -c "cd /root/app/ && gcc server.c -o server && ./server"
    ports:
      - "53:53/udp"
    networks:
      - hogar

  #client:
  #build: ./cliente
  #container_name: cliente
  #command: bash -c "nslookup https://w3.cs.jmu.edu/kirkpams/OpenCSF/Books/csf/html/UDPSockets.html"
  #command: bash -c "nslookup www.google.com"
  #depends_on:
  #  - cserver
  #volumes:
  #  - ./cliente/resolv.conf:/etc/resolv.conf
  #networks:
  #  - hogar

  restapi:
    build: 
      context: ./ #carpeta con el dockerfile
      dockerfile: Dockerfile # Archivo de imagen 
    ports: 
    - "443:443"  

networks:
  hogar:
    ipam:
      config:
        - subnet: 1.0.0.0/29

