version: '3.7' #sudo docker-compose up -d     #sudo docker-compose build

services:
  cserver:
    build: ./cserver
    container_name: cserver
    volumes:
      - ./cserver:/root/app
    command: bash -c "cd /root/app/ && gcc -o server server.c -lcurl && ./server"
    ports:
      - "53:53/udp"   
    #network_mode: host

  restapi:
    build: 
      context: ./restapi #carpeta con el dockerfile
      dockerfile: Dockerfile # Archivo de imagen 
    container_name: restapi
    ports: 
    - "443:443"  
    #networks:
    #  - hogar 
        
  #elasticsearch:
  #  container_name: elasticsearch
  #  image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
  #  restart: always
  #  environment:
  #    - discovery.type=single-node
  #  ulimits:
  #    memlock:
  #      soft: -1
  #      hard: -1
  #    nofile:
  #      soft: 65536
  #      hard: 65536
  #  cap_add:
  #    - IPC_LOCK
  #  volumes:
  #    - elasticsearch-data-volume:/usr/share/elasticsearch/data
  #  ports:
  #    - 9200:9200
  #
  #kibana:
  #  container_name: kibana
  #  image: docker.elastic.co/kibana/kibana:7.8.1
  #  restart: always
  #  environment:
  #    - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
  #  ports:
  #    - 5601:5601
  #  volumes:
  #    - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
  #  depends_on:
  #    - elasticsearch

volumes:
  elasticsearch-data-volume:
    driver: local